// <auto-generated />
using System.Diagnostics.CodeAnalysis;using System.Diagnostics;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Dataverse.Linq.Tests.Proxies
{
    /// <summary>
    /// Proxy class that represents the 'new_customaccount' D365 table
    /// </summary>
    [EntityLogicalNameAttribute("new_customaccount")]
    [GeneratedCode("XrmToolkit", "8.3.4.0")]
    [DataContract(Name = "Entity", Namespace = "http://schemas.microsoft.com/xrm/2011/Contracts")]
    [DebuggerNonUserCode]
    [ExcludeFromCodeCoverage]
    public partial class CustomAccount : BaseProxyClass
    {
        public new const string LogicalName = "new_customaccount";
        public const int ObjectTypeCode = 11223;
        public const string PrimaryIdAttribute = "new_customaccountid";
        public const string PrimaryNameAttribute = "new_name";
        
        static CustomAccount()
        {
            BaseProxyClass.RegisterProxyType(typeof(CustomAccount), "new_customaccount");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public CustomAccount() : base(new Entity("new_customaccount")) { }
        public CustomAccount(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<CustomAccount>(); }

        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }

        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }

        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }

        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }

        private static Dictionary<string, eNumberOptions> _numberOptions;

        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }

        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }

        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }
        /// <summary>
        /// Logical Name: new_accountrating
        /// </summary>
        [AttributeLogicalName("new_accountrating")]
        public AccountRating_Enum? AccountRating
        {
            get
            {
                if (AccountRating_OptionSetValue != null) { return (AccountRating_Enum)AccountRating_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.AccountRating_OptionSetValue = new OptionSetValue((int)value); }
                else this.AccountRating_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_accountrating</para>
        /// </summary>
        [AttributeLogicalName("new_accountrating")]
        public OptionSetValue AccountRating_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("new_accountrating");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("new_accountrating", value, nameof(AccountRating_OptionSetValue));
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="service">D365 Organization Service</param>
        /// <returns></returns>
        public string AccountRating_Text(IOrganizationService service)
        {
            return this.AccountRating_OptionSetValue.GetOptionSetText(service, this, "new_accountrating");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="attributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string AccountRating_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.AccountRating_OptionSetValue.Value);
        }

        /// <summary>
        /// <para>Logical Name: createdby</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("createdby");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfby</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdon</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("createdon");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdbyname")]
        public string CreatedByName
        {
            get
            {
                return this.GetPropertyValue<string>("createdbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdbyyominame")]
        public string CreatedByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("createdbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfbyname")]
        public string CreatedOnBehalfByName
        {
            get
            {
                return this.GetPropertyValue<string>("createdonbehalfbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfbyyominame")]
        public string CreatedOnBehalfByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("createdonbehalfbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_creditlimit</para>
        /// <para>Minimum Value: -922337203685477</para>
        /// <para>Maximum Value: 922337203685477</para>
        /// <para>Precision: 2</para>
        /// </summary>
        [AttributeLogicalName("new_creditlimit")]
        public decimal? CreditLimit
        {
            get
            {
                if (CreditLimitMoney != null) { return CreditLimitMoney.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.CreditLimitMoney = new Money(value.Value); }
                else this.CreditLimitMoney = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_creditlimit</para>
        /// <para>Minimum Value: -922337203685477</para>
        /// <para>Maximum Value: 922337203685477</para>
        /// <para>Precision: 2</para>
        /// </summary>
        [AttributeLogicalName("new_creditlimit")]
        public Money CreditLimitMoney
        {
            get
            {
                return this.GetPropertyValue<Money>("new_creditlimit");
            }
            set
            {
                this.SetPropertyValue("new_creditlimit", (Money)value, (decimal)-922337203685477, (decimal)922337203685477, nameof(CreditLimitMoney));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_creditlimit_base</para>
        /// <para>Minimum Value: -922337203685477</para>
        /// <para>Maximum Value: 922337203685477</para>
        /// <para>Precision: 2</para>
        /// </summary>
        [AttributeLogicalName("new_creditlimit_base")]
        public decimal? CreditLimit_Base
        {
            get
            {
                if (CreditLimit_BaseMoney != null) { return CreditLimit_BaseMoney.Value; }
                return null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_creditlimit_base</para>
        /// <para>Minimum Value: -922337203685477</para>
        /// <para>Maximum Value: 922337203685477</para>
        /// <para>Precision: 2</para>
        /// </summary>
        [AttributeLogicalName("new_creditlimit_base")]
        public Money CreditLimit_BaseMoney
        {
            get
            {
                return this.GetPropertyValue<Money>("new_creditlimit_base");
            }
        }

        /// <summary>
        /// <para>Logical Name: transactioncurrencyid</para>
        /// </summary>
        [AttributeLogicalName("transactioncurrencyid")]
        public EntityReference Currency
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetPropertyValue<EntityReference>("transactioncurrencyid", value, nameof(Currency));
            }
        }

        /// <summary>
        /// <para>Key Property (Uniqueidentifier)</para>
        /// <para>Logical Name: new_customaccountid</para>
        /// </summary>
        [AttributeLogicalName("new_customaccountid")]
        public Guid CustomAccountId
        {
            get
            {
                return base.Attributes.Contains("new_customaccountid") ? this.GetAttributeValue<Guid>("new_customaccountid") : base.Id;
            }
            set
            {
                base.Id = value;
                base.Attributes["new_customaccountid"] = value;
                base.SetPropertyValue("new_customaccountid", value, nameof(CustomAccountId));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_datecompanywasorganized</para>
        /// </summary>
        [AttributeLogicalName("new_datecompanywasorganized")]
        public DateTime? DateCompanyWasOrganized
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("new_datecompanywasorganized");
            }
            set
            {
                this.SetPropertyValue<DateTime?>("new_datecompanywasorganized", value, nameof(DateCompanyWasOrganized));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_description</para>
        /// <para>Max Length: 2000 characters</para>
        /// </summary>
        [AttributeLogicalName("new_description")]
        public string Description
        {
            get
            {
                return this.GetPropertyValue<string>("new_description");
            }
            set
            {
                this.SetPropertyValue("new_description", value, 2000, nameof(Description));
            }
        }

        /// <summary>
        /// <para>Logical Name: exchangerate</para>
        /// <para>Minimum Value: 0.0000000001</para>
        /// <para>Maximum Value: 100000000000</para>
        /// <para>Precision: 10</para>
        /// </summary>
        [AttributeLogicalName("exchangerate")]
        public decimal? ExchangeRate
        {
            get
            {
                return this.GetPropertyValue<decimal?>("exchangerate");
            }
        }

        /// <summary>
        /// <para>Logical Name: importsequencenumber</para>
        /// <para>Minimum Value: -2147483648</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("importsequencenumber");
            }
            set
            {
                this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, nameof(ImportSequenceNumber));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_ispreferredaccount</para>
        /// <para>True = Yes</para>
        /// <para>False = No</para>
        /// </summary>
        [AttributeLogicalName("new_ispreferredaccount")]
        public bool? IsPreferredAccount
        {
            get
            {
                return this.GetPropertyValue<bool?>("new_ispreferredaccount");
            }
            set
            {
                this.SetPropertyValue<bool?>("new_ispreferredaccount", value, nameof(IsPreferredAccount));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_latitude</para>
        /// <para>Minimum Value: -90</para>
        /// <para>Maximum Value: 90</para>
        /// <para>Precision: 5</para>
        /// </summary>
        [AttributeLogicalName("new_latitude")]
        public double? Latitude
        {
            get
            {
                return this.GetPropertyValue<double?>("new_latitude");
            }
            set
            {
                this.SetPropertyValue("new_latitude", (double?)value, (double)-90, (double)90, nameof(Latitude));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_longitude</para>
        /// <para>Minimum Value: -180</para>
        /// <para>Maximum Value: 180</para>
        /// <para>Precision: 5</para>
        /// </summary>
        [AttributeLogicalName("new_longitude")]
        public double? Longitude
        {
            get
            {
                return this.GetPropertyValue<double?>("new_longitude");
            }
            set
            {
                this.SetPropertyValue("new_longitude", (double?)value, (double)-180, (double)180, nameof(Longitude));
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedby</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfby</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedon</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("modifiedon");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedbyname")]
        public string ModifiedByName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedbyyominame")]
        public string ModifiedByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfbyname")]
        public string ModifiedOnBehalfByName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedonbehalfbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfbyyominame")]
        public string ModifiedOnBehalfByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedonbehalfbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_name</para>
        /// <para>Max Length: 850 characters</para>
        /// </summary>
        [AttributeLogicalName("new_name")]
        public string Name
        {
            get
            {
                return this.GetPropertyValue<string>("new_name");
            }
            set
            {
                this.SetPropertyValue("new_name", value, 850, nameof(Name));
            }
        }



        /// <summary>
        /// <para>Logical Name: new_parentaccountname</para>
        /// <para>Max Length: 850 characters</para>
        /// </summary>
        [AttributeLogicalName("new_parentaccountname")]
        public string new_ParentAccountName
        {
            get
            {
                return this.GetPropertyValue<string>("new_parentaccountname");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_primarycontactname</para>
        /// <para>Max Length: 850 characters</para>
        /// </summary>
        [AttributeLogicalName("new_primarycontactname")]
        public string new_PrimaryContactName
        {
            get
            {
                return this.GetPropertyValue<string>("new_primarycontactname");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_numberofemployees</para>
        /// <para>Minimum Value: 0</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("new_numberofemployees")]
        public int? NumberOfEmployees
        {
            get
            {
                return this.GetPropertyValue<int?>("new_numberofemployees");
            }
            set
            {
                this.SetPropertyValue("new_numberofemployees", (int?)value, (int)0, (int)2147483647, nameof(NumberOfEmployees));
            }
        }

        /// <summary>
        /// <para>Logical Name: ownerid</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference Owner
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("ownerid");
            }
            set
            {
                this.SetPropertyValue<EntityReference>("ownerid", value, nameof(Owner));
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("owneridname")]
        public string OwnerIdName
        {
            get
            {
                return this.GetPropertyValue<string>("owneridname");
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridtype</para>
        /// </summary>
        [AttributeLogicalName("owneridtype")]
        public string OwnerIdType
        {
            get
            {
                return this.GetPropertyValue<string>("owneridtype");
            }
            set
            {
                this.SetPropertyValue<string>("owneridtype", value, nameof(OwnerIdType));
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("owneridyominame")]
        public string OwnerIdYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("owneridyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: owningbusinessunit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// <para>Logical Name: owningteam</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// <para>Logical Name: owninguser</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// <para>Logical Name: owningbusinessunitname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunitname")]
        public string OwningBusinessUnitName
        {
            get
            {
                return this.GetPropertyValue<string>("owningbusinessunitname");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_parentaccount</para>
        /// </summary>
        [AttributeLogicalName("new_parentaccount")]
        public EntityReference ParentAccount
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("new_parentaccount");
            }
            set
            {
                this.SetPropertyValue<EntityReference>("new_parentaccount", value, nameof(ParentAccount));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_percentcomplete</para>
        /// <para>Minimum Value: 0</para>
        /// <para>Maximum Value: 100</para>
        /// <para>Precision: 2</para>
        /// </summary>
        [AttributeLogicalName("new_percentcomplete")]
        public decimal? PercentComplete
        {
            get
            {
                return this.GetPropertyValue<decimal?>("new_percentcomplete");
            }
            set
            {
                this.SetPropertyValue("new_percentcomplete", (decimal?)value, (decimal)0, (decimal)100, nameof(PercentComplete));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_primarycontact</para>
        /// </summary>
        [AttributeLogicalName("new_primarycontact")]
        public EntityReference PrimaryContact
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("new_primarycontact");
            }
            set
            {
                this.SetPropertyValue<EntityReference>("new_primarycontact", value, nameof(PrimaryContact));
            }
        }

        /// <summary>
        /// <para>Logical Name: new_primaryemail</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("new_primaryemail")]
        public string PrimaryEmail
        {
            get
            {
                return this.GetPropertyValue<string>("new_primaryemail");
            }
            set
            {
                this.SetPropertyValue("new_primaryemail", value, 100, nameof(PrimaryEmail));
            }
        }

        /// <summary>
        /// <para>Logical Name: overriddencreatedon</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        public DateTime? RecordCreatedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("overriddencreatedon");
            }
            set
            {
                this.SetPropertyValue<DateTime?>("overriddencreatedon", value, nameof(RecordCreatedOn));
            }
        }


        /// <summary>
        /// Logical Name: statecode
        /// </summary>
        [AttributeLogicalName("statecode")]
        public CustomAccount_Status? Status
        {
            get
            {
                if (Status_OptionSetValue != null) { return (CustomAccount_Status)Status_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.Status_OptionSetValue = new OptionSetValue((int)value); }
                else this.Status_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: statecode</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        public OptionSetValue Status_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("statecode");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("statecode", value, nameof(Status_OptionSetValue));
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="service">D365 Organization Service</param>
        /// <returns></returns>
        public string Status_Text(IOrganizationService service)
        {
            return this.Status_OptionSetValue.GetOptionSetText(service, this, "statecode");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="attributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string Status_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.Status_OptionSetValue.Value);
        }

        /// <summary>
        /// Logical Name: statuscode
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public CustomAccount_StatusReason? StatusReason
        {
            get
            {
                if (StatusReason_OptionSetValue != null) { return (CustomAccount_StatusReason)StatusReason_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.StatusReason_OptionSetValue = new OptionSetValue((int)value); }
                else this.StatusReason_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: statuscode</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public OptionSetValue StatusReason_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("statuscode");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("statuscode", value, nameof(StatusReason_OptionSetValue));
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="service">D365 Organization Service</param>
        /// <returns></returns>
        public string StatusReason_Text(IOrganizationService service)
        {
            return this.StatusReason_OptionSetValue.GetOptionSetText(service, this, "statuscode");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="attributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string StatusReason_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.StatusReason_OptionSetValue.Value);
        }


        /// <summary>
        /// <para>Logical Name: timezoneruleversionnumber</para>
        /// <para>Minimum Value: -1</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        public int? TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("timezoneruleversionnumber");
            }
            set
            {
                this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, nameof(TimeZoneRuleVersionNumber));
            }
        }

        /// <summary>
        /// <para>Logical Name: transactioncurrencyidname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("transactioncurrencyidname")]
        public string TransactionCurrencyIdName
        {
            get
            {
                return this.GetPropertyValue<string>("transactioncurrencyidname");
            }
        }

        /// <summary>
        /// <para>Logical Name: utcconversiontimezonecode</para>
        /// <para>Minimum Value: -1</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        public int? UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetPropertyValue<int?>("utcconversiontimezonecode");
            }
            set
            {
                this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, nameof(UTCConversionTimeZoneCode));
            }
        }

        /// <summary>
        /// <para>Logical Name: versionnumber</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public int? VersionNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("versionnumber");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_website</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("new_website")]
        public string Website
        {
            get
            {
                return this.GetPropertyValue<string>("new_website");
            }
            set
            {
                this.SetPropertyValue("new_website", value, 100, nameof(Website));
            }
        }


        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_customaccount_AsyncOperations</para>
        /// </summary>
        public List<Entity> GetSystemJobs_Regarding(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "asyncoperation", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_customaccount_AsyncOperations</para>
        /// </summary>
        public List<Entity> GetSystemJobs_Regarding(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "asyncoperation", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Name)</b></para>
        /// <para>Schema Name: new_customaccount_BulkDeleteFailures</para>
        /// </summary>
        public List<Entity> GetBulkDeleteFailures_Name(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "bulkdeletefailure", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Name)</b></para>
        /// <para>Schema Name: new_customaccount_BulkDeleteFailures</para>
        /// </summary>
        public List<Entity> GetBulkDeleteFailures_Name(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "bulkdeletefailure", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding Object Id)</b></para>
        /// <para>Schema Name: new_customaccount_MailboxTrackingFolders</para>
        /// </summary>
        public List<Entity> GetMailboxAutoTrackingFolders_RegardingObjectId(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "mailboxtrackingfolder", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding Object Id)</b></para>
        /// <para>Schema Name: new_customaccount_MailboxTrackingFolders</para>
        /// </summary>
        public List<Entity> GetMailboxAutoTrackingFolders_RegardingObjectId(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "mailboxtrackingfolder", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>CustomAccount (Parent Account)</b></para>
        /// <para>Schema Name: new_customaccount_ParentAccount_new_customaccount</para>
        /// </summary>
        public List<CustomAccount> GetCustomAccounts_ParentAccount(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CustomAccount>(service, this.Id, "new_customaccount", "new_parentaccount", columns); }

        /// <summary>
        /// <para><b>CustomAccount (Parent Account)</b></para>
        /// <para>Schema Name: new_customaccount_ParentAccount_new_customaccount</para>
        /// </summary>
        public List<CustomAccount> GetCustomAccounts_ParentAccount(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CustomAccount>(service, this.Id, "new_customaccount", "new_parentaccount", columns); }

        /// <summary>
        /// <para><b>CustomContact (Parent Account)</b></para>
        /// <para>Schema Name: new_customcontact_ParentAccount_new_customaccount</para>
        /// </summary>
        public List<CustomContact> GetCustomContacts_ParentAccount(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CustomContact>(service, this.Id, "new_customcontact", "new_parentaccount", columns); }

        /// <summary>
        /// <para><b>CustomContact (Parent Account)</b></para>
        /// <para>Schema Name: new_customcontact_ParentAccount_new_customaccount</para>
        /// </summary>
        public List<CustomContact> GetCustomContacts_ParentAccount(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CustomContact>(service, this.Id, "new_customcontact", "new_parentaccount", columns); }

        /// <summary>
        /// <para><b>Entity (Entity instance)</b></para>
        /// <para>Schema Name: new_customaccount_PrincipalObjectAttributeAccesses</para>
        /// </summary>
        public List<Entity> GetFieldSharing_EntityInstance(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "principalobjectattributeaccess", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Entity instance)</b></para>
        /// <para>Schema Name: new_customaccount_PrincipalObjectAttributeAccesses</para>
        /// </summary>
        public List<Entity> GetFieldSharing_EntityInstance(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "principalobjectattributeaccess", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_customaccount_ProcessSession</para>
        /// </summary>
        public List<Entity> GetProcessSessions_Regarding(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "processsession", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_customaccount_ProcessSession</para>
        /// </summary>
        public List<Entity> GetProcessSessions_Regarding(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "processsession", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Record)</b></para>
        /// <para>Schema Name: new_customaccount_SyncErrors</para>
        /// </summary>
        public List<Entity> GetSyncErrors_Record(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "syncerror", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Record)</b></para>
        /// <para>Schema Name: new_customaccount_SyncErrors</para>
        /// </summary>
        public List<Entity> GetSyncErrors_Record(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "syncerror", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Object Id)</b></para>
        /// <para>Schema Name: new_customaccount_UserEntityInstanceDatas</para>
        /// </summary>
        public List<Entity> GetUserEntityInstanceData_ObjectId(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "userentityinstancedata", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Object Id)</b></para>
        /// <para>Schema Name: new_customaccount_UserEntityInstanceDatas</para>
        /// </summary>
        public List<Entity> GetUserEntityInstanceData_ObjectId(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "userentityinstancedata", "objectid", columns); }


        
        
        public enum AccountRating_Enum
        {
            /// <summary>
            /// <para>Cold</para>
            /// <para>Value = 100000000</para>
            /// </summary>
            [Description("Cold")]
            Cold = 100000000,

            /// <summary>
            /// <para>Warm</para>
            /// <para>Value = 100000001</para>
            /// </summary>
            [Description("Warm")]
            Warm = 100000001,

            /// <summary>
            /// <para>Hot</para>
            /// <para>Value = 100000002</para>
            /// </summary>
            [Description("Hot")]
            Hot = 100000002,
        }
        public enum CustomAccount_Status
        {
            /// <summary>
            /// <para>Active</para>
            /// <para>Value = 0</para>
            /// </summary>
            [Description("Active")]
            Active = 0,

            /// <summary>
            /// <para>Inactive</para>
            /// <para>Value = 1</para>
            /// </summary>
            [Description("Inactive")]
            Inactive = 1,
        }
        public enum CustomAccount_StatusReason
        {
            /// <summary>
            /// <para>Active</para>
            /// <para>Value = 1</para>
            /// </summary>
            [Description("Active")]
            Active = 1,

            /// <summary>
            /// <para>Inactive</para>
            /// <para>Value = 2</para>
            /// </summary>
            [Description("Inactive")]
            Inactive = 2,
        }
        public void SetState(IOrganizationService service, CustomAccount_Status state, CustomAccount_StatusReason status)
        {
            service.SetState(this, (int)state, (int)status);
        }
        public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService service, CustomAccount_Status state, CustomAccount_StatusReason status)
        {
            await service.SetStateAsync(this, (int)state, (int)status);
        }

        public static class Properties
        {
            /// <summary>
            /// <para>Account Rating</para>
            /// <para>Logical Name = new_accountrating</para>
            /// </summary>
            public const string AccountRating = "new_accountrating";

            /// <summary>
            /// <para>Created By</para>
            /// <para>Logical Name = createdby</para>
            /// </summary>
            public const string CreatedBy = "createdby";

            /// <summary>
            /// <para>Created By (Delegate)</para>
            /// <para>Logical Name = createdonbehalfby</para>
            /// </summary>
            public const string CreatedBy_Delegate = "createdonbehalfby";

            /// <summary>
            /// <para>Created On</para>
            /// <para>Logical Name = createdon</para>
            /// </summary>
            public const string CreatedOn = "createdon";

            /// <summary>
            /// <para>CreatedByName</para>
            /// <para>Logical Name = createdbyname</para>
            /// </summary>
            public const string CreatedByName = "createdbyname";

            /// <summary>
            /// <para>CreatedByYomiName</para>
            /// <para>Logical Name = createdbyyominame</para>
            /// </summary>
            public const string CreatedByYomiName = "createdbyyominame";

            /// <summary>
            /// <para>CreatedOnBehalfByName</para>
            /// <para>Logical Name = createdonbehalfbyname</para>
            /// </summary>
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";

            /// <summary>
            /// <para>CreatedOnBehalfByYomiName</para>
            /// <para>Logical Name = createdonbehalfbyyominame</para>
            /// </summary>
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";

            /// <summary>
            /// <para>Credit Limit</para>
            /// <para>Logical Name = new_creditlimit</para>
            /// </summary>
            public const string CreditLimit = "new_creditlimit";

            /// <summary>
            /// <para>Credit Limit (Base)</para>
            /// <para>Logical Name = new_creditlimit_base</para>
            /// </summary>
            public const string CreditLimit_Base = "new_creditlimit_base";

            /// <summary>
            /// <para>Currency</para>
            /// <para>Logical Name = transactioncurrencyid</para>
            /// </summary>
            public const string Currency = "transactioncurrencyid";

            /// <summary>
            /// <para>Custom Account</para>
            /// <para>Logical Name = new_customaccountid</para>
            /// </summary>
            public const string CustomAccountId = "new_customaccountid";

            /// <summary>
            /// <para>Date Company Was Organized</para>
            /// <para>Logical Name = new_datecompanywasorganized</para>
            /// </summary>
            public const string DateCompanyWasOrganized = "new_datecompanywasorganized";

            /// <summary>
            /// <para>Description</para>
            /// <para>Logical Name = new_description</para>
            /// </summary>
            public const string Description = "new_description";

            /// <summary>
            /// <para>Exchange Rate</para>
            /// <para>Logical Name = exchangerate</para>
            /// </summary>
            public const string ExchangeRate = "exchangerate";

            /// <summary>
            /// <para>Import Sequence Number</para>
            /// <para>Logical Name = importsequencenumber</para>
            /// </summary>
            public const string ImportSequenceNumber = "importsequencenumber";

            /// <summary>
            /// <para>Is Preferred Account</para>
            /// <para>Logical Name = new_ispreferredaccount</para>
            /// </summary>
            public const string IsPreferredAccount = "new_ispreferredaccount";

            /// <summary>
            /// <para>Latitude</para>
            /// <para>Logical Name = new_latitude</para>
            /// </summary>
            public const string Latitude = "new_latitude";

            /// <summary>
            /// <para>Longitude</para>
            /// <para>Logical Name = new_longitude</para>
            /// </summary>
            public const string Longitude = "new_longitude";

            /// <summary>
            /// <para>Modified By</para>
            /// <para>Logical Name = modifiedby</para>
            /// </summary>
            public const string ModifiedBy = "modifiedby";

            /// <summary>
            /// <para>Modified By (Delegate)</para>
            /// <para>Logical Name = modifiedonbehalfby</para>
            /// </summary>
            public const string ModifiedBy_Delegate = "modifiedonbehalfby";

            /// <summary>
            /// <para>Modified On</para>
            /// <para>Logical Name = modifiedon</para>
            /// </summary>
            public const string ModifiedOn = "modifiedon";

            /// <summary>
            /// <para>ModifiedByName</para>
            /// <para>Logical Name = modifiedbyname</para>
            /// </summary>
            public const string ModifiedByName = "modifiedbyname";

            /// <summary>
            /// <para>ModifiedByYomiName</para>
            /// <para>Logical Name = modifiedbyyominame</para>
            /// </summary>
            public const string ModifiedByYomiName = "modifiedbyyominame";

            /// <summary>
            /// <para>ModifiedOnBehalfByName</para>
            /// <para>Logical Name = modifiedonbehalfbyname</para>
            /// </summary>
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";

            /// <summary>
            /// <para>ModifiedOnBehalfByYomiName</para>
            /// <para>Logical Name = modifiedonbehalfbyyominame</para>
            /// </summary>
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";

            /// <summary>
            /// <para>Name</para>
            /// <para>Logical Name = new_name</para>
            /// </summary>
            public const string Name = "new_name";

            /// <summary>
            /// <para>new_accountratingName</para>
            /// <para>Logical Name = new_accountratingname</para>
            /// </summary>
            public const string new_accountratingName = "new_accountratingname";

            /// <summary>
            /// <para>new_ispreferredaccountName</para>
            /// <para>Logical Name = new_ispreferredaccountname</para>
            /// </summary>
            public const string new_ispreferredaccountName = "new_ispreferredaccountname";

            /// <summary>
            /// <para>new_ParentAccountName</para>
            /// <para>Logical Name = new_parentaccountname</para>
            /// </summary>
            public const string new_ParentAccountName = "new_parentaccountname";

            /// <summary>
            /// <para>new_PrimaryContactName</para>
            /// <para>Logical Name = new_primarycontactname</para>
            /// </summary>
            public const string new_PrimaryContactName = "new_primarycontactname";

            /// <summary>
            /// <para>Number Of Employees</para>
            /// <para>Logical Name = new_numberofemployees</para>
            /// </summary>
            public const string NumberOfEmployees = "new_numberofemployees";

            /// <summary>
            /// <para>Owner</para>
            /// <para>Logical Name = ownerid</para>
            /// </summary>
            public const string Owner = "ownerid";

            /// <summary>
            /// <para>OwnerIdName</para>
            /// <para>Logical Name = owneridname</para>
            /// </summary>
            public const string OwnerIdName = "owneridname";

            /// <summary>
            /// <para>OwnerIdType</para>
            /// <para>Logical Name = owneridtype</para>
            /// </summary>
            public const string OwnerIdType = "owneridtype";

            /// <summary>
            /// <para>OwnerIdYomiName</para>
            /// <para>Logical Name = owneridyominame</para>
            /// </summary>
            public const string OwnerIdYomiName = "owneridyominame";

            /// <summary>
            /// <para>Owning Business Unit</para>
            /// <para>Logical Name = owningbusinessunit</para>
            /// </summary>
            public const string OwningBusinessUnit = "owningbusinessunit";

            /// <summary>
            /// <para>Owning Team</para>
            /// <para>Logical Name = owningteam</para>
            /// </summary>
            public const string OwningTeam = "owningteam";

            /// <summary>
            /// <para>Owning User</para>
            /// <para>Logical Name = owninguser</para>
            /// </summary>
            public const string OwningUser = "owninguser";

            /// <summary>
            /// <para>OwningBusinessUnitName</para>
            /// <para>Logical Name = owningbusinessunitname</para>
            /// </summary>
            public const string OwningBusinessUnitName = "owningbusinessunitname";

            /// <summary>
            /// <para>Parent Account</para>
            /// <para>Logical Name = new_parentaccount</para>
            /// </summary>
            public const string ParentAccount = "new_parentaccount";

            /// <summary>
            /// <para>Percent Complete</para>
            /// <para>Logical Name = new_percentcomplete</para>
            /// </summary>
            public const string PercentComplete = "new_percentcomplete";

            /// <summary>
            /// <para>Primary Contact</para>
            /// <para>Logical Name = new_primarycontact</para>
            /// </summary>
            public const string PrimaryContact = "new_primarycontact";

            /// <summary>
            /// <para>Primary Email</para>
            /// <para>Logical Name = new_primaryemail</para>
            /// </summary>
            public const string PrimaryEmail = "new_primaryemail";

            /// <summary>
            /// <para>Record Created On</para>
            /// <para>Logical Name = overriddencreatedon</para>
            /// </summary>
            public const string RecordCreatedOn = "overriddencreatedon";

            /// <summary>
            /// <para>statecodeName</para>
            /// <para>Logical Name = statecodename</para>
            /// </summary>
            public const string statecodeName = "statecodename";

            /// <summary>
            /// <para>Status</para>
            /// <para>Logical Name = statecode</para>
            /// </summary>
            public const string Status = "statecode";

            /// <summary>
            /// <para>Status Reason</para>
            /// <para>Logical Name = statuscode</para>
            /// </summary>
            public const string StatusReason = "statuscode";

            /// <summary>
            /// <para>statuscodeName</para>
            /// <para>Logical Name = statuscodename</para>
            /// </summary>
            public const string statuscodeName = "statuscodename";

            /// <summary>
            /// <para>Time Zone Rule Version Number</para>
            /// <para>Logical Name = timezoneruleversionnumber</para>
            /// </summary>
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";

            /// <summary>
            /// <para>TransactionCurrencyIdName</para>
            /// <para>Logical Name = transactioncurrencyidname</para>
            /// </summary>
            public const string TransactionCurrencyIdName = "transactioncurrencyidname";

            /// <summary>
            /// <para>UTC Conversion Time Zone Code</para>
            /// <para>Logical Name = utcconversiontimezonecode</para>
            /// </summary>
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";

            /// <summary>
            /// <para>Version Number</para>
            /// <para>Logical Name = versionnumber</para>
            /// </summary>
            public const string VersionNumber = "versionnumber";

            /// <summary>
            /// <para>Website</para>
            /// <para>Logical Name = new_website</para>
            /// </summary>
            public const string Website = "new_website";

        }

    }
}
